# import re
# from playwright.sync_api import Page, expect


# def test_example(page: Page) -> None:
#     page.goto("https://hywebdemo.com/medora/admin/login")
#     page.get_by_role("textbox", name="Enter Email Address").click()
#     page.get_by_role("textbox", name="Enter Email Address").click()
#     page.get_by_role("textbox", name="Enter Email Address").fill("kaviyarasu@hyrrokkin.net")
#     page.get_by_role("button", name="Send OTP").click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("textbox").first.click()
#     page.get_by_role("textbox").first.press("NumLock")
#     page.get_by_role("textbox").first.fill("1")
#     page.get_by_role("textbox").nth(1).fill("2")
#     page.get_by_role("textbox").nth(2).fill("3")
#     page.get_by_role("textbox").nth(3).fill("4")
#     page.get_by_role("textbox").nth(4).fill("5")
#     page.get_by_role("textbox").nth(5).fill("6")
#     page.wait_for_timeout(3000)
#     page.get_by_role("button", name="Verify & Login").click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("link", name=" Master").click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("link", name=" Country").click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("link", name=" Create").click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("textbox", name="Enter country name").click()
#     page.get_by_role("textbox", name="Enter country name").fill("newsland")
#     page.wait_for_timeout(3000)
#     page.get_by_role("textbox", name="Enter country code (e.g., IND)").click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("textbox", name="Enter country code (e.g., IND)").fill("NEW")
#     page.wait_for_timeout(3000)
#     page.get_by_role("button", name="Save").click()
#     page.wait_for_timeout(3000)
#     page.locator(".edit").first.click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("textbox", name="Enter country name").click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("textbox", name="Enter country code (e.g., IND)").click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("button", name="Update").click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("button").filter(has_text=re.compile(r"^$")).click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("row", name="Bangladesh BD Active   ").get_by_role("button").click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("button", name="Yes").click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("row", name="Bangladesh BD Inactive   ").get_by_role("button").click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("button", name="Yes").click()
#     page.wait_for_timeout(3000)
#     page.locator(".view").first.click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("button").filter(has_text=re.compile(r"^$")).click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("combobox").select_option("1")
#     page.wait_for_timeout(3000)
#     page.get_by_role("button", name=" Filter").click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("link", name="Reset").click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("combobox").select_option("0")
#     page.wait_for_timeout(3000)
#     page.get_by_role("button", name=" Filter").click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("link", name="Reset").click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("searchbox", name="Enter country name or code").click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("searchbox", name="Enter country name or code").fill("bangladesh")
#     page.wait_for_timeout(3000)
#     page.get_by_role("button", name=" Filter").click()
#     page.wait_for_timeout(3000)
#     page.get_by_role("link", name="Reset").click()
#     page.wait_for_timeout(3000)
#     page.locator("div").filter(has_text="Country Search Status Select").nth(2).click()
#     page.wait_for_timeout(3000)
#     expect(page.get_by_role("searchbox", name="Enter country name or code")).to_be_visible()
#     page.wait_for_timeout(3000)
